# try:
    # Statement which could generate
    # Exception
# except:
      # Solution of generated exception
# finally:
      # block of code which is going to
      # execute in any situation

____________________________________________________________________________________________________________________________________________________________________

# a = input("Enter the number: ")
# print(f"Multiplication table of {a} is: ")

# try:
#     for i in range(1, 11):
#         print(f"{int(a)} X {i} = {int(a) * i}")
# except Exception as e:
#     print("Invalid Input")

# print("Some imp lines of code")
# print("End of program")

# try:
#    num = int(input("Enter an integer: "))
#    print("You've entered an integer value.")
 #except ValueError:
#    print("Number entered is not an integer.")




def func1():
    try:
        l = [1, 5, 6, 7]
        i = int(input("Enter the index: "))
        print(l[i])
        return 1
    except:
        print("Some error occured")
        return 0
    finally:
        print("I am always executed")

x = func1()
print(x)


def even_num():
#     try:
#         num = int(input("Enter the number: "))
#         if num % 2 == 0:
#             print("Even number")
#         else:
#             print("Odd number")
#     except:
#         print("Invalid Input")
#     finally:
#         print("I am always executed if I'm even or odd number")

# x = even_num()
# print(x)









































































